version: '3.9'
services:
  bingo-leaderboard:
    container_name: bingo-leaderboard
    build:
      context: .
    image: bingo-leaderboard
    volumes:
      - /bingo-leaderboard/volume:/etc/bingo-leaderboard
    ports:
      - "14445:8080"
    restart: unless-stopped

networks:
  default:
    name: nginx
    external: true